class Priorities:
    """
    Priorities of standard operators.
    """
    OPERATOR_AND = 200
    OPERATOR_EQUAL = 300
    OPERATOR_GREATER = 400
    OPERATOR_GREATER_OR_EQUAL = 400
    OPERATOR_LESS = 400
    OPERATOR_LESS_OR_EQUAL = 400
    OPERATOR_NOT = 600
    OPERATOR_NOT_EQUAL = 300
    OPERATOR_OR = 100
    OPERATOR_PLUS = 500
